services:
  api:
    build:
      context: ./preset_service
    ports:
      - "8000:8000"

  web:
    build:
      context: ./flutter_preset_app
    ports:
      - "8080:80"
    depends_on:
      - api

